// <auto-generated />
using System;
using InvestAdvisor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestAdvisor.Data.Migrations
{
    [DbContext(typeof(InvestAdvisorDbContext))]
    [Migration("20260611105400_AddLlmProviderSettings")]
    partial class AddLlmProviderSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("InvestAdvisor.Core.Entities.AdviceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ParseFallbackUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsedConsiderationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedDriftAlertsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedFlagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedPositionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedSummary")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReplayOfAdviceLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructuredInputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPromptUsed")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReplayOfAdviceLogId");

                    b.HasIndex("TimestampUtc")
                        .IsDescending();

                    b.ToTable("AdviceLog", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.AlertDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdviceLogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("AdviceLogId", "Channel");

                    b.ToTable("AlertDelivery", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.AnalystRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Buy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sell")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrongBuy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrongSell")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Period")
                        .IsUnique();

                    b.ToTable("AnalystRating", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.DailyRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CryptoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EtfsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StocksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAtUtc");

                    b.ToTable("DailyRecommendation", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetClass")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetAllocationPct")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "AccountType");

                    b.ToTable("Holding", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.InsiderTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Change")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDerivative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "FilingDate");

                    b.ToTable("InsiderTrade", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.NewsItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentimentLabel")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("decimal(4,3)");

                    b.Property<DateTime?>("SentimentScoredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SentimentScoredAtUtc");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Ticker", "PublishedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("NewsItem", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.PriceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentChange")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousClose")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "FetchedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("PriceSnapshot", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DriftPctThreshold")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalsText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RebalanceCadenceHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskTolerance")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SingleDayMovePctThreshold")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPromptOverride")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeHorizon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.RuntimeSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgentPaused")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyBudgetUsd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoldingsCsvPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldingsCsvUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmCustomBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmRoutineModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarketHoursOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRunsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSnapshotAgeForTriggerSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPriceFreshnessSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSecondsBetweenRuns")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmtpEnableSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpFrom")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpTo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TickIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightAnalyst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightGrowth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightInsider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightMomentum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightSentiment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightValuation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RuntimeSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentPaused = false,
                            DailyBudgetUsd = 2m,
                            DarkMode = false,
                            EmailEnabled = false,
                            LlmModel = "gemini-2.5-flash",
                            LlmProvider = "gemini",
                            LlmRoutineModel = "gemini-2.5-flash-lite",
                            MarketHoursOnly = true,
                            MaxRunsPerDay = 12,
                            MaxSnapshotAgeForTriggerSeconds = 600,
                            MinPriceFreshnessSeconds = 60,
                            MinSecondsBetweenRuns = 1800,
                            SmtpEnableSsl = true,
                            SmtpPort = 587,
                            TickIntervalSeconds = 300,
                            TimeZoneId = "America/New_York",
                            UpdatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightAnalyst = 20,
                            WeightGrowth = 25,
                            WeightInsider = 10,
                            WeightMomentum = 15,
                            WeightQuality = 10,
                            WeightSentiment = 10,
                            WeightValuation = 20
                        });
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.ScreenerScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AsOfDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CompositeScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("Ticker", "AsOfDate")
                        .IsUnique();

                    b.ToTable("ScreenerScore", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.SentimentRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsScored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAtUtc");

                    b.ToTable("SentimentRun", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetClass");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.StockAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BearishFactorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BullishFactorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CompositeScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Conviction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConvictionLabel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyRisksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thesis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "GeneratedAtUtc");

                    b.ToTable("StockAnalysis", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.StockMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Beta")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DebtToEquity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EpsGrowthPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MarketCap")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MomentumLong")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MomentumShort")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PeRatio")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceToFreeCashFlow")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RevenueGrowthPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "FetchedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("StockMetric", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceTargetHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceTargetLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "AssetClass")
                        .IsUnique();

                    b.ToTable("WatchlistItem", (string)null);
                });

            modelBuilder.Entity("InvestAdvisor.Core.Entities.AlertDelivery", b =>
                {
                    b.HasOne("InvestAdvisor.Core.Entities.AdviceLog", "AdviceLog")
                        .WithMany()
                        .HasForeignKey("AdviceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdviceLog");
                });
#pragma warning restore 612, 618
        }
    }
}
